name: Integration Test

on:
  push:
    branches:
      - integration-test
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kind
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: "v0.24.0"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Set up ko
        uses: ko-build/setup-ko@v0.8

      - name: Testing
        run: |
          kubectl cluster-info
          kubectl version
          kubectl get pods -n kube-system

      - name: Build image with ko
        run: |
          ./hack/kind-build.sh

      - name: Deploy test resources
        run: |
          ./hack/kind-deploy.sh
          ./hack/kind-moonlander-test-mocks.sh

      - name: Run integration tests
        run: |
          ./hack/kind-test.sh

      - name: Cleanup
        if: always()
        run: |
          kubectl delete -k deploy/test/ || true
          kubectl delete -f test/yaml/ || true
          helm uninstall -n urmanac moonlander-crd
